
from typing import Final

SCR_WIDTH: Final = 1200
SCR_HEIGHT: Final = 550
FPS: Final = 60

GATE_WIDTH = 100
NODE_SIZE = 10
NODE_SPACING = 20

GRID_SIZE = 8

GATE_TEXT_BORDER_OFFSET_X = 20
GATE_TEXT_BORDER_OFFSET_Y = 5

DEFAULT_CIRCUIT_NAME = '_'

CIRCUIT_INPUT_NODES_ID = 'CIRCUIT_INPUT_NODES_ID'
CIRCUIT_OUTPUT_NODES_ID = 'CIRCUIT_OUTPUT_NODES_ID'
CIRCUIT_WIRE_CONNECTED_TRACKER_ID = 'CIRCUIT_WIRE_CONNECTED_TRACKER_ID'
CIRCUIT_WIRE_ID = 'CIRCUIT_WIRE_ID'
CIRCUIT_GATE_ID = 'CIRCUIT_GATE_ID'
CIRCUIT_WIRE_LEFT_PRESSED_ID = 'CIRCUIT_WIRE_LEFT_PRESSED_ID'
CIRCUIT_WIRE_RIGHT_PRESSED_ID = 'CIRCUIT_WIRE_RIGHT_PRESSED_ID'
CIRCUIT_INPUT_BUTTON_REMOVALS_ID = 'CIRCUIT_INPUT_BUTTON_REMOVALS_ID'
CIRCUIT_OUTPUT_BUTTON_REMOVALS_ID = 'CIRCUIT_OUTPUT_BUTTON_REMOVALS_ID'
CIRCUIT_GATE_KEY_INDEX_MAP_ID = 'CIRCUIT_GATE_KEY_INDEX_MAP_ID',
GATE_ID = 'GATE_ID'

DEFAULT_CIRCUIT: dict[str, list] = {
    CIRCUIT_WIRE_ID: [],
    CIRCUIT_GATE_ID: [],
    CIRCUIT_INPUT_NODES_ID: [],
    CIRCUIT_OUTPUT_NODES_ID: [],
    CIRCUIT_GATE_KEY_INDEX_MAP_ID: {},
    CIRCUIT_WIRE_CONNECTED_TRACKER_ID: {},
    CIRCUIT_WIRE_LEFT_PRESSED_ID: True,
    CIRCUIT_WIRE_RIGHT_PRESSED_ID: True,
    CIRCUIT_INPUT_BUTTON_REMOVALS_ID: False,
    CIRCUIT_OUTPUT_BUTTON_REMOVALS_ID: False,
    GATE_ID: None
}


